-- begin IMPROVETABLE_CLIENT
alter table IMPROVETABLE_CLIENT add constraint FK_IMPROVETABLE_CLIENT_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_IMPROVETABLE_CLIENT_MANAGER on IMPROVETABLE_CLIENT (MANAGER_ID)^
-- end IMPROVETABLE_CLIENT
